apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argocd-nginx
  name: argocd-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argocd-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
